
import java.sql.*;
import java.io.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author itspgiri
 */
public class TaskList extends javax.swing.JFrame {

    /**
     * Creates new form TaskList
     */
    public TaskList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showTasks = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskList = new javax.swing.JTable();
        signout = new javax.swing.JButton();
        taskcomplete = new javax.swing.JButton();
        logoText = new javax.swing.JLabel();
        welcomeText1 = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        showTasks2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        descInput = new javax.swing.JTextArea();
        titleInput = new javax.swing.JTextField();
        addtask = new javax.swing.JButton();
        welcomeText2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showTasks.setBackground(new java.awt.Color(99, 88, 220));
        showTasks.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        showTasks.setForeground(new java.awt.Color(255, 255, 255));
        showTasks.setText("Show Tasks");
        showTasks.setBorderPainted(false);
        showTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTasksActionPerformed(evt);
            }
        });
        getContentPane().add(showTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 110, 40));

        TaskList.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        TaskList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TaskList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 450, 140));

        signout.setBackground(new java.awt.Color(99, 88, 220));
        signout.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        getContentPane().add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 90, 40));

        taskcomplete.setBackground(new java.awt.Color(99, 88, 220));
        taskcomplete.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        taskcomplete.setForeground(new java.awt.Color(255, 255, 255));
        taskcomplete.setText("Mark Task As Completed");
        taskcomplete.setBorderPainted(false);
        taskcomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskcompleteActionPerformed(evt);
            }
        });
        getContentPane().add(taskcomplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 437, 450, 40));

        logoText.setFont(new java.awt.Font("Raleway ExtraBold", 1, 64)); // NOI18N
        logoText.setForeground(new java.awt.Color(99, 88, 220));
        logoText.setText("TodoList");
        getContentPane().add(logoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        welcomeText1.setFont(new java.awt.Font("Poppins", 0, 32)); // NOI18N
        welcomeText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(welcomeText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 30, -1));

        idInput.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        idInput.setForeground(new java.awt.Color(128, 128, 128));
        idInput.setToolTipText("");
        idInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter TaskID", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        idInput.setCaretColor(new java.awt.Color(99, 88, 220));
        idInput.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        idInput.setDoubleBuffered(true);
        idInput.setDragEnabled(true);
        idInput.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });
        getContentPane().add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 450, 50));
        idInput.getAccessibleContext().setAccessibleName("Task Title");

        showTasks2.setBackground(new java.awt.Color(99, 88, 220));
        showTasks2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        showTasks2.setForeground(new java.awt.Color(255, 255, 255));
        showTasks2.setText("Refresh");
        showTasks2.setBorderPainted(false);
        showTasks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTasks2ActionPerformed(evt);
            }
        });
        getContentPane().add(showTasks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 80, 40));

        descInput.setColumns(20);
        descInput.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        descInput.setForeground(new java.awt.Color(128, 128, 128));
        descInput.setRows(5);
        descInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(128, 128, 128))); // NOI18N
        jScrollPane3.setViewportView(descInput);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 450, 150));

        titleInput.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        titleInput.setForeground(new java.awt.Color(128, 128, 128));
        titleInput.setToolTipText("");
        titleInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Title", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        titleInput.setCaretColor(new java.awt.Color(99, 88, 220));
        titleInput.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        titleInput.setDoubleBuffered(true);
        titleInput.setDragEnabled(true);
        titleInput.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        titleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleInputActionPerformed(evt);
            }
        });
        getContentPane().add(titleInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 450, 50));

        addtask.setBackground(new java.awt.Color(99, 88, 220));
        addtask.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        addtask.setForeground(new java.awt.Color(255, 255, 255));
        addtask.setText("Add Task");
        addtask.setBorderPainted(false);
        addtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtaskActionPerformed(evt);
            }
        });
        getContentPane().add(addtask, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 450, 40));

        welcomeText2.setFont(new java.awt.Font("Poppins", 0, 32)); // NOI18N
        welcomeText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText2.setText("Welcome to");
        getContentPane().add(welcomeText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void showTask(){
        try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/todoist","root","password");
        Statement st = con.createStatement();
        String query="Select * FROM Task";
        ResultSet rs = st.executeQuery(query);
        ResultSetMetaData rsmd = rs.getMetaData();
        DefaultTableModel model = (DefaultTableModel) TaskList.getModel();
    int cols = rsmd.getColumnCount();
        String[] colName = new String[cols];
        for (int i=0; i<cols;i++)
        {
            colName[i] = rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            
        }
        String taskID, taskName, taskDesc;
        while(rs.next()){
           taskID = rs.getString(1);
           taskName = rs.getString(2);
           taskDesc = rs.getString(3);
           String[] row = {taskID, taskName, taskDesc};
           model.addRow(row);
        }
        st.close();
        con.close();
        signout.setVisible(true);
        showTasks.setVisible(false);
        }
        catch (ClassNotFoundException e)
        {
            System.out.print("Task List ClassNotFound");
        }
        catch (SQLException ex) {
            Logger.getLogger(TaskList.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void showTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTasksActionPerformed
      showTask();  // TODO add your handling code here:
    
    }//GEN-LAST:event_showTasksActionPerformed

    private void taskcompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskcompleteActionPerformed
int t = Integer.parseInt(idInput.getText());
try
{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/todoist","root","password");
    Statement st = con.createStatement();
    String query= "DELETE FROM Task WHERE TaskID = "+t+";";
    st.executeUpdate(query);
    JOptionPane.showMessageDialog(null,"Task Deleted - Refresh to see updated Task List");

}
catch (Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_taskcompleteActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void showTasks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTasks2ActionPerformed
    TaskList.setModel(new DefaultTableModel());
    showTask();
    }//GEN-LAST:event_showTasks2ActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
this.setVisible(false);
Home n = new Home();
n.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_signoutActionPerformed

    private void titleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleInputActionPerformed

    private void addtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtaskActionPerformed
String title = new String(titleInput.getText());
String desc = new String(descInput.getText());
try
{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/todoist","root","password");
    Statement st = con.createStatement();
    String query= "INSERT INTO `todoist`.`task` (`TaskName`, `TaskDesc`) VALUES ('"+title+"', '"+desc+"');";
    st.executeUpdate(query);
    JOptionPane.showMessageDialog(null,"Task Added - Refresh to see updated Task List");

}
catch (Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
// TODO add your handling code here:
    }//GEN-LAST:event_addtaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TaskList;
    private javax.swing.JButton addtask;
    private javax.swing.JTextArea descInput;
    private javax.swing.JTextField idInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoText;
    private javax.swing.JButton showTasks;
    private javax.swing.JButton showTasks2;
    private javax.swing.JButton signout;
    private javax.swing.JButton taskcomplete;
    private javax.swing.JTextField titleInput;
    private javax.swing.JLabel welcomeText1;
    private javax.swing.JLabel welcomeText2;
    // End of variables declaration//GEN-END:variables
}
